### PR TITLE
Feature/profile pic

### PR DESCRIPTION
**Pull request by shetty-shithil**
@swarajpure I've added the user profile-pic besides the greeting message.

### CODE REVIEW

**Review by swarajpure — CHANGES_REQUESTED** [review]
Please revert the client id to the original one
Also, please run `npm run fix` to fix the formatting which is causing the tests to fail. Please commit and push to the same branch after both the changes are done.

Thank you 😁

**Review by Rucha1499 — CHANGES_REQUESTED** [review]
Good work! @shetty-shithil 🎉 

Can you please add the screenshots of your changes? 

Also one check is failing. Please have a look at it!

**Comment by shetty-shithil** [comment]
Okay.

**Comment by shetty-shithil** [comment]
@Rucha1499 and @swarajpure, I have done required changes. 
Screenshot (2061)
Screenshot (2062)
Screenshot (2063)

**Review by swarajpure — CHANGES_REQUESTED** [review]
There seem to a lot of unnecessary formatting changes, `prettier` needs to be configured. @Rucha1499 please look into this

Also by screenshots, she meant the UI screenshots 😅 
We can see the code on github as well 😅 

Thanks!

**Comment by shetty-shithil** [comment]
Okay!
Screenshot (2059)

**Pull request closed without merging**
