### PR TITLE
fixed faq buttons

### LINKED ISSUE #88: Fix the FAQ page - Changing of +/- signs
- In the below image, the sign should be `-` when clicked on the question, according to desired behaviour.

image

### PR DESCRIPTION
**Pull request by DaniManas**
Fixes #88

### CODE REVIEW

**Review by Rucha1499 — COMMENTED** [review]
Congratulations on your first PR in RDS!! 🎉 

Can you please add some screenshots/ video of your changes to the description of PR ? It becomes easy to review it! Thank you.

**Comment by DaniManas** [comment]
https://imgur.com/9pMxTsi

**Review by swarajpure — APPROVED** [review]
Congratulations on your first pull requests in RDS!

Thank you: 🎉

**Review by Rucha1499 — APPROVED** [review]
Great!! Thank you 🎉

**Pull request merged**
