### PR TITLE
fixed and refactored discord page

### LINKED ISSUE #196: Fix discord page CSS in `develop` branch
Currently we are redesigning the welcome site and the design is partially implemented. Whatever is implemented is merged in `develop` branch and is deployed to https://staging-welcome.realdevsquad.com, this code will eventually be merged to the `main` branch

Old, stable version of code is in `main` branch and is deployed to https://welcome.realdevsquad.com

Now if you see the Discord page in both of the versions, something is broken. What is broken? That is up to you to find out and fix (pretty easy to identify if you compare both the versions side by side)

Links for you to compare:
https://staging-welcome.realdevsquad.com/discord.html
https://welcome.realdevsquad.com/discord.html

### PR DESCRIPTION
**Pull request by Ishikabaid**
closes #196 
1. Fixed the alignment issues of discord page
2. Refactored CSS of discord page
3. Fixed issue with `stay tuned` text.

### CODE REVIEW

**Review by rohan09-raj — CHANGES_REQUESTED** [review]
IMG_20211231_111841

Can you please make the following changes :
1- Added left-right margin/padding to the text shown in image.
2 - Apply some media query to the image to make it  a bit responsive (if you are using flexbox then simply changing the width would work in the media query)

**Review by Rucha1499 — CHANGES_REQUESTED** [review]
Thanks for this PR! @Ishikabaid 😄 

Adding some comments. Kindly have a look
image
Can we fix this please?

Rest everything looks good!

**Review by rohan09-raj — CHANGES_REQUESTED** [review]
image
Can we center align this please by adding equivalent margin to left also ?

**Review by Rucha1499 — APPROVED** [review]
Looks good to me! ✨

**Pull request merged**
