### PR TITLE
Setting up prettier CLI

### PR DESCRIPTION
**Pull request by swarajpure**

### CODE REVIEW

**Comment by swarajpure** [comment]
Chose wrong branch to push 🤦🏻‍♂️

**Comment by swarajpure** [comment]
Even on some branch, I'm seeing ashish's commits, weird

**Review by Rucha1499 — APPROVED** [review]
Looks great!!  @swarajpure 🔥 🎉 

Thank you so much!!

**Comment by swarajpure** [comment]
The problem was that I had extra 11 commits (most of them by ashish) in my local develop. Since I had rebased this branch, those commits also got added here. 

How did I fix?
I reverted my local develop to the initial commit and then did a git pull for a clean commit history.
I anyway had to discard this `feature/prettier-cli` branch as it had to extra 11 commits and I couldn't reset this branch and get the changes again, I would have lost this commit which is actually useful.
So what I did was, created a branch `feat/node-prettier` from develop and then used `git cherrypick` command to add this useful commit on top of the clean develop history and it worked smooth, no merge conflicts to be solved.

Closing this PR. New PR reference #120

**Pull request closed without merging**
