### PR TITLE
Fix- css changes for discord page

### PR DESCRIPTION
**Pull request by karnsweta92**
#55 Changes are done in css and html page is formatted.
@strider99 Kindly review.

### CODE REVIEW

**Review by swarajpure — COMMENTED** [review]
Can you please add photos of before and after your changes?
Would be easy to understand what changes have taken place 😄

**Comment by karnsweta92** [comment]
> Can you please add photos of before and after your changes?
> Would be easy to understand what changes have taken place 😄
Attached image for reference
AfterChanges
BeforeChanges

**Review by swarajpure — CHANGES_REQUESTED** [review]
Would be good if things are center aligned.
Also could the channel description made in tabular format? with some styling the table, that might look good.
The screenshot seems to be of bad quality, can be improved?

**Comment by karnsweta92** [comment]
@swarajpure Yes.I am working on it.

**Comment by karnsweta92** [comment]
Changes in discord pages are done to match the UI  of other pages.
Its design is similar to the FAQ page in design & layout.
Refer to attached screenshot.
SS1
SS2
SS3

**Comment by karnsweta92** [comment]
@strider99 Kindly review.

**Comment by Rucha1499** [comment]
This issue is solved. Closing the PR . Ref : https://welcome.realdevsquad.com/discord.html

**Pull request closed without merging**
