### PR TITLE
Addition of nonreferrer attribute in links

### PR DESCRIPTION
**Pull request by shetty-shithil**
@Rucha1499 
I have added the required security feature for external links in **index.html**, also made a small grammatical correction in **CONTRIBUTING.md**.

### CODE REVIEW

**Review by Rucha1499 — APPROVED** [review]
Congratulations on your first PR in RDS!! @shetty-shithil 🎉 

Thanks for fixing the issue and the changes in CONTRIBUTING.md. 👍

**Comment by shetty-shithil** [comment]
Thank you @Rucha1499.

**Review by swarajpure — CHANGES_REQUESTED** [review]
Congratulations on your first pull request in Real Dev Squad! 🎉 

Can we please have the `noreferrer` attribute instead? More on that here: https://web.dev/external-anchors-use-rel-noopener/

Also, can you please rename the PR title as to what it is supposed to do? Something like `adds norefferer attribute to links`

**Comment by shetty-shithil** [comment]
Okay.

**Review by swarajpure — APPROVED** [review]
Looks good!

Approving from my side! 😁

**Pull request merged**
