### PR TITLE
DOM manipulated as per required behaviour issue#136

### PR DESCRIPTION
**Pull request by iRahulP**
updated behaviour for inactive nodes irrespective of current selection of FAQ being closed or open by the user.

### CODE REVIEW

**Review by Rucha1499 — COMMENTED** [review]
Thanks for the PR! @iRahulP 🎉 

Can you please add a small video/gif of the working of FAQ icons after the changes to the description of PR ? It becomes easy to review. 😃 Kindly link the issue number to the PR.

**Comment by iRahulP** [comment]
https://user-images.githubusercontent.com/26308074/111881663-907cbd00-89d7-11eb-9706-e64177d64f81.mp4

Hi @Rucha1499, I have updated the required results above. Also I am unable to link the required issue : https://github.com/Real-Dev-Squad/website-welcome/issues/136 to this PR.

Is there any specific write access level required for this project after which I will be able to link the issue as well as add reveiwers and updated other things like adding labels/assignees, Everything seems to be grayed out for me.

**Comment by Rucha1499** [comment]
Thanks for adding the video! 👍 
image
Also this itself is linking the issue. There is no other way to link it. 😄

**Review by Rucha1499 — APPROVED** [review]
Great! Thanks for the fixes! 🔥

**Pull request merged**
